name: Build and deploy Node.js app to Azure Web App - tech0-gen-8-step3-testapp-node1-8

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup Project
        run: |
          # Initial setup
          npm install
          
          # Install tailwind and its dependencies
          npm install -D tailwindcss postcss autoprefixer
          npm install -D @types/node
          
          # Initialize tailwind if not already initialized
          npx tailwindcss init -p
          
          # Install shadcn-ui dependencies
          npm install @radix-ui/react-slot
          npm install class-variance-authority
          npm install clsx
          npm install tailwind-merge
          npm install lucide-react
          
          # Create components directory structure
          mkdir -p components/ui
          
          # Initialize shadcn-ui
          npx shadcn-ui@latest init -y
          
          # Add specific components
          npx shadcn-ui@latest add button -y
          npx shadcn-ui@latest add input -y
          npx shadcn-ui@latest add card -y

      - name: Create component files
        run: |
          # Create button component
          cat > components/ui/button.jsx << 'EOL'
          import * as React from "react"
          import { Slot } from "@radix-ui/react-slot"
          import { cva } from "class-variance-authority"
          import { cn } from "@/lib/utils"
          
          const buttonVariants = cva(
            "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
            {
              variants: {
                variant: {
                  default: "bg-primary text-primary-foreground hover:bg-primary/90",
                  destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
                  outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
                  secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
                  ghost: "hover:bg-accent hover:text-accent-foreground",
                  link: "text-primary underline-offset-4 hover:underline",
                },
                size: {
                  default: "h-10 px-4 py-2",
                  sm: "h-9 rounded-md px-3",
                  lg: "h-11 rounded-md px-8",
                  icon: "h-10 w-10",
                },
              },
              defaultVariants: {
                variant: "default",
                size: "default",
              },
            }
          )
          
          const Button = React.forwardRef(({ className, variant, size, asChild = false, ...props }, ref) => {
            const Comp = asChild ? Slot : "button"
            return (
              <Comp
                className={cn(buttonVariants({ variant, size, className }))}
                ref={ref}
                {...props}
              />
            )
          })
          Button.displayName = "Button"
          
          export { Button, buttonVariants }
          EOL
          
          # Create input component
          cat > components/ui/input.jsx << 'EOL'
          import * as React from "react"
          import { cn } from "@/lib/utils"
          
          const Input = React.forwardRef(({ className, type, ...props }, ref) => {
            return (
              <input
                type={type}
                className={cn(
                  "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
                  className
                )}
                ref={ref}
                {...props}
              />
            )
          })
          Input.displayName = "Input"
          
          export { Input }
          EOL
          
          # Create card components
          cat > components/ui/card.jsx << 'EOL'
          import * as React from "react"
          import { cn } from "@/lib/utils"
          
          const Card = React.forwardRef(({ className, ...props }, ref) => (
            <div
              ref={ref}
              className={cn(
                "rounded-lg border bg-card text-card-foreground shadow-sm",
                className
              )}
              {...props}
            />
          ))
          Card.displayName = "Card"
          
          const CardHeader = React.forwardRef(({ className, ...props }, ref) => (
            <div
              ref={ref}
              className={cn("flex flex-col space-y-1.5 p-6", className)}
              {...props}
            />
          ))
          CardHeader.displayName = "CardHeader"
          
          const CardTitle = React.forwardRef(({ className, ...props }, ref) => (
            <h3
              ref={ref}
              className={cn(
                "text-2xl font-semibold leading-none tracking-tight",
                className
              )}
              {...props}
            />
          ))
          CardTitle.displayName = "CardTitle"
          
          const CardDescription = React.forwardRef(({ className, ...props }, ref) => (
            <p
              ref={ref}
              className={cn("text-sm text-muted-foreground", className)}
              {...props}
            />
          ))
          CardDescription.displayName = "CardDescription"
          
          const CardContent = React.forwardRef(({ className, ...props }, ref) => (
            <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
          ))
          CardContent.displayName = "CardContent"
          
          const CardFooter = React.forwardRef(({ className, ...props }, ref) => (
            <div
              ref={ref}
              className={cn("flex items-center p-6 pt-0", className)}
              {...props}
            />
          ))
          CardFooter.displayName = "CardFooter"
          
          export { Card, CardHeader, CardFoot
